seed: 42

additional_features:
  ema:
    alphas: [0.05, 0.3, 0.8]

train:
  n_folds: 5
  dataloader:
    num_workers: 4
    batch_size: 16
  optimizer:
    lr: 5e-4
  loop:
    accelerator: mps
    max_epochs: 100
  early_stopping:
    patience: 3
    min_delta: 1e-3
  model:
    in_size: 32
    in_ema_size: 96
    in_proj: 128
    hidden_size: 256
    num_layers: 1
    dropout: 0
    out_size: 32
    warmup_steps: 100
